export const PARAMS_CHARACTER_TYPE = {
  SELECT_FIELD: 1,
  CHAR_FIELD: 2,
  TEXT_FIELD: 3,
  NUMBER_FIELD: 4,
  IMAGE_FIELD: 5,
  VIDEO_FIELD: 6,
  AUDIO_FIELD: 7,
  FILE_FIELD: 8,
  BOOLEAN_FIELD: 9,
  DATE_FIELD: 10,
  COLOUR_FIELD: 11,
  YEAR_FIELD: 12
};
