export const URL_KEYS = {
    STEP: 'step',
    MENU_TYPE: 'menu_type',
    SEARCH_TYPE: 'search_type',
    BOTTOM_MENU: 'bottom_menu',
    VERIFICATION_STEP: 'verification_step',
    SETTINGS_TYPE: 'settings_type',
    SPECIALIST_ID: 'specialist_id',
    OFFERING_GROUP_ID: 'offering_group_id',
    SPECIALIST_CATEGORY_ID: 'specialist_category_id',
    CHAT_TAB: 'chat_tabs',
    SEARCH: 'search',
    TAB: 'tab',
    ACCOUNT: 'account',
    TAPE_TYPE: 'tape_type',
    DATE: 'date',
    TIME: 'time',
    TEXT: 'text',
    NEXT: 'next',
    CATEGORY: 'category'
}

export const URL_VALUES = {
    WORK: 'work',
    STEP: 'step',
    GROUP: 'group',
    STREAM: 'stream',
    PEOPLE: 'people',
    PRODUCT: 'product',
    ACCOUNT: 'account',
    DWED_FAQ: 'dwed_faq',
    SETTINGS: 'settings',
    OVERVIEW: 'overview',
    LANGUAGE: 'language',
    COMPANIES: 'companies',
    OFFERINGS: 'offerings',
    FOLLOWERS: 'followers',
    FOLLOWING: 'following',
    ALL_CHATS: 'all_chats',
    GROUP_CHATS: 'group_chats',
    PHONE_VERIFY: 'phone_verify',
    CHANGE_PHONE: 'change_phone',
    NOTIFICATION: 'notification',
    ORGANIZATION: 'organization',
    PAYMENT_METHODS: 'payment_methods',
    ACCOUNT_MAIN_DATA: 'account_main_data',
    ORGANIZATION_DATA: 'organization_data',
    CREATE_ORGANIZATION: 'create_organization',
    PERSONAL_INFORMATION: 'personal_information'
}